/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as CoachesLoginRouteImport } from './routes/coaches.login'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesLoginRoute = CoachesLoginRouteImport.update({
  id: '/coaches/login',
  path: '/coaches/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/support': typeof SupportRoute
  '/coaches/login': typeof CoachesLoginRoute
  '/coaches/': typeof CoachesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/support': typeof SupportRoute
  '/coaches/login': typeof CoachesLoginRoute
  '/coaches': typeof CoachesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/support': typeof SupportRoute
  '/coaches/login': typeof CoachesLoginRoute
  '/coaches/': typeof CoachesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/join'
    | '/news'
    | '/support'
    | '/coaches/login'
    | '/coaches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/join'
    | '/news'
    | '/support'
    | '/coaches/login'
    | '/coaches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/join'
    | '/news'
    | '/support'
    | '/coaches/login'
    | '/coaches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  NewsRoute: typeof NewsRoute
  SupportRoute: typeof SupportRoute
  CoachesLoginRoute: typeof CoachesLoginRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/login': {
      id: '/coaches/login'
      path: '/coaches/login'
      fullPath: '/coaches/login'
      preLoaderRoute: typeof CoachesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  NewsRoute: NewsRoute,
  SupportRoute: SupportRoute,
  CoachesLoginRoute: CoachesLoginRoute,
  CoachesIndexRoute: CoachesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
